FROM python:3.11.9-slim

WORKDIR /llms/tutorials/llm-from-scratch-book

RUN python -m pip install -U pip \
    && pip install --no-cache-dir -U numpy==1.26.4 matplotlib==3.8.4 pytest==8.2.0 \
    && pip install --no-cache-dir torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu \
    && export PYTHONPATH=.

COPY tests ./tests
COPY src ./src

CMD ["python", "-m", "pytest", "-v"]