name: Pytest testing
run-name: ${{ github.actor }} is testing python code!
on:
  pull_request:
    branches:
      - master
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install torch==2.4.0 --index-url https://download.pytorch.org/whl/cpu && \
            pip install transformers==4.43.2
          pip install pytest
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Test with pytest
        run: |
          python -m pytest tests
      - run: echo "🍏 This job's status is ${{ job.status }}."